### ISSUE TITLE
Quality check of the fingerprint

### ISSUE THREAD

**Issue by PumaTechCPT** [rainxh11/ZkTecoFingerPrint#1]
Hi

Is there a way to check the quality/clarity of a fingerprint scan with a method?

I have attached photos when you press hard and touch it lightly.

Thanks !
![ONENOTE_GN3MF37MJ5](https://github.com/user-attachments/assets/21bc595d-d048-4122-9a27-7517859e1f91)

**Comment by rainxh11** [comment]
There's is no existing free or open-source library that i know of that can compare fingerprints quality 
If you know of a library that accomplish that, i'll happily port it to C# and add it to the project

**Comment by PumaTechCPT** [comment]
I couldn’t find a library to check fingerprint quality, so I came up with a method to do it myself. I measure how bright the black areas are in the image/bitmap and then compare it to a value I figured out from testing. This helps me determine if the fingerprint quality is good enough.

**Comment by alextnull** [comment]
It looks like this is possible using the NFIQ2 software.
https://github.com/usnistgov/NFIQ2
